namespace SlimeColorShop
{
    public enum ColorQuestionEncyclopediaStateEnum
    {
        UNKNOWN,
        NAME_KNOWN,
        HEX_CODE_KNOWN,
        NAME_AND_HEX_CODE_KNOWN,
        LIKE_PHRASE_KNOWN,
        LIKE_PHRASE_AND_NAME_KNOWN,
        LIKE_PHRASE_AND_HEX_CODE_KNOWN,
        LIKE_PHRASE_AND_HEX_CODE_AND_NAME_KNOWN,
        COMBINATION_PHRASE_KNOWN,
        COMBINATION_PHRASE_AND_NAME_KNOWN,
        COMBINATION_PHRASE_AND_HEX_CODE_KNOWN,
        COMBINATION_PHRASE_AND_NAME_AND_HEX_CODE_KNOWN,
        COMBINATION_PHRASE_AND_LIKE_PHRASE_KNOWN,
        COMBINATION_PHRASE_AND_LIKE_PHRASE_AND_NAME_KNOWN,
        COMBINATION_PHRASE_AND_LIKE_PHRASE_AND_HEX_CODE_KNOWN,
        COMBINATION_PHRASE_AND_LIKE_PHRASE_AND_HEX_CODE_AND_NAME_KNOWN
    }
}
